package com.hoon.dustsearch.model.MsrstnAcctoRltmMesureDnsty

import com.google.gson.annotations.SerializedName

data class MsrstnAcctoRltmMesureDnsty(@SerializedName("coGrade") val coGrade: String,
                                      @SerializedName("coValue") val coValue: String,
                                      @SerializedName("dataTerm") val dataTerm: String,
                                      @SerializedName("dataTime") val dataTime: String,
                                      @SerializedName("khaiGrade") val khaiGrade: String,
                                      @SerializedName("khaiValue") val khaiValue: String,
                                      @SerializedName("mangName") val mangName: String,
                                      @SerializedName("no2Grade") val no2Grade: String,
                                      @SerializedName("no2Value") val no2Value: String,
                                      @SerializedName("numOfRows") val numOfRows: String,
                                      @SerializedName("o3Grade") val o3Grade: String,
                                      @SerializedName("o3Value") val o3Value: String,
                                      @SerializedName("pageNo") val pageNo: String,
                                      @SerializedName("pm10Grade") val pm10Grade: String,
                                      @SerializedName("pm10Grade1h") val pm10Grade1h: String,
                                      @SerializedName("pm10Value") val pm10Value: String,
                                      @SerializedName("pm10Value24") val pm10Value24: String,
                                      @SerializedName("pm25Grade") val pm25Grade: String,
                                      @SerializedName("pm25Grade1h") val pm25Grade1h: String,
                                      @SerializedName("pm25Value") val pm25Value: String,
                                      @SerializedName("pm25Value24") val pm25Value24: String,
                                      @SerializedName("resultCode") val resultCode: String,
                                      @SerializedName("resultMsg") val resultMsg: String,
                                      @SerializedName("rnum") val rnum: Int,
                                      @SerializedName("serviceKey") val serviceKey: String,
                                      @SerializedName("sidoName") val sidoName: String,
                                      @SerializedName("so2Grade") val so2Grade: String,
                                      @SerializedName("so2Value") val so2Value: String,
                                      @SerializedName("stationCode") val stationCode: String,
                                      @SerializedName("stationName") val stationName: String,
                                      @SerializedName("totalCount") val totalCount: String,
                                      @SerializedName("ver") val ver: String,
                                      @SerializedName("_returnType") val _returnType: String)